name = "scary fish"
author = "scarysoda6"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4eb3efeabf45786e06d2cae19b265ea0fc7c37376a09cb2463a1ca010467012"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = ["1.21.1", "1.21+", "1.21.x"]
