name = "scary fish"
author = "scarysoda6"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6864cc5cbcd8b6b18198e6702b2bd3b0407019befb5c66bc491a72c78784a3ef"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = ["1.21.1", "1.21+", "1.21.x"]
