name = "scary fish"
author = "scarysoda6"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bef6e897ada7128e8a13209da1d76494b79d892c429d61f8767afd46b1fab87"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = ["1.21.1", "1.21+", "1.21.x"]
